name: testjar

on:
  push
  
jobs:
  build:
    runs-on: ubuntu-latest
    
  steps:
    name: checkout code
    uses: actions/checkout@v2
    
    name: setup java
    uses: actions/setup-java@v1
    with:
          java-version: 1.8
          server-id: sonatype-nexus-staging
          server-username: ${{ secrets.OSSRH_USER }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          
    run:
      mvn clean install
      
          
    
    
    
